language: d

os:
  - osx
  - linux

d:
 - ldc-1.3.0
 - ldc-1.2.0
 - ldc-1.1.0
 - ldc-1.0.0
 - dmd-beta
 - dmd-2.075.0
 - dmd-2.074.1
 - dmd-2.073.1
 - dmd-2.072.1
 
script:

 dub test --compiler=${DC}
